// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HZMsg
{

using global::System;
using global::FlatBuffers;

public struct Bond : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Bond __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int A1 { get { return __p.bb.GetInt(__p.bb_pos + 0); } }
  public void MutateA1(int a1) { __p.bb.PutInt(__p.bb_pos + 0, a1); }
  public int A2 { get { return __p.bb.GetInt(__p.bb_pos + 4); } }
  public void MutateA2(int a2) { __p.bb.PutInt(__p.bb_pos + 4, a2); }
  public int T { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public void MutateT(int t) { __p.bb.PutInt(__p.bb_pos + 8, t); }

  public static Offset<Bond> CreateBond(FlatBufferBuilder builder, int A1, int A2, int T) {
    builder.Prep(4, 12);
    builder.PutInt(T);
    builder.PutInt(A2);
    builder.PutInt(A1);
    return new Offset<Bond>(builder.Offset);
  }
};


}
