// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HZMsg
{

using global::System;
using global::FlatBuffers;

public struct Frame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Frame GetRootAsFrame(ByteBuffer _bb) { return GetRootAsFrame(_bb, new Frame()); }
  public static Frame GetRootAsFrame(ByteBuffer _bb, Frame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Frame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int N { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Scalar4? Positions(int j) { int o = __p.__offset(6); return o != 0 ? (Scalar4?)(new Scalar4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int PositionsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Frame> CreateFrame(FlatBufferBuilder builder,
      int N = 0,
      VectorOffset positionsOffset = default(VectorOffset)) {
    builder.StartObject(2);
    Frame.AddPositions(builder, positionsOffset);
    Frame.AddN(builder, N);
    return Frame.EndFrame(builder);
  }

  public static void StartFrame(FlatBufferBuilder builder) { builder.StartObject(2); }
  public static void AddN(FlatBufferBuilder builder, int N) { builder.AddInt(0, N, 0); }
  public static void AddPositions(FlatBufferBuilder builder, VectorOffset positionsOffset) { builder.AddOffset(1, positionsOffset.Value, 0); }
  public static void StartPositionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static Offset<Frame> EndFrame(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Frame>(o);
  }
  public static void FinishFrameBuffer(FlatBufferBuilder builder, Offset<Frame> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFrameBuffer(FlatBufferBuilder builder, Offset<Frame> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
