// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace HZMsg
{

using global::System;
using global::FlatBuffers;

public struct Frame : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Frame GetRootAsFrame(ByteBuffer _bb) { return GetRootAsFrame(_bb, new Frame()); }
  public static Frame GetRootAsFrame(ByteBuffer _bb, Frame obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Frame __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int N { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateN(int N) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, N); return true; } else { return false; } }
  public int I { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateI(int I) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, I); return true; } else { return false; } }
  public int Time { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateTime(int time) { int o = __p.__offset(8); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, time); return true; } else { return false; } }
  public Scalar4? Positions(int j) { int o = __p.__offset(10); return o != 0 ? (Scalar4?)(new Scalar4()).__assign(__p.__vector(o) + j * 16, __p.bb) : null; }
  public int PositionsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Bond? Bonds(int j) { int o = __p.__offset(12); return o != 0 ? (Bond?)(new Bond()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int BondsLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Frame> CreateFrame(FlatBufferBuilder builder,
      int N = 0,
      int I = 0,
      int time = 0,
      VectorOffset positionsOffset = default(VectorOffset),
      VectorOffset bondsOffset = default(VectorOffset)) {
    builder.StartObject(5);
    Frame.AddBonds(builder, bondsOffset);
    Frame.AddPositions(builder, positionsOffset);
    Frame.AddTime(builder, time);
    Frame.AddI(builder, I);
    Frame.AddN(builder, N);
    return Frame.EndFrame(builder);
  }

  public static void StartFrame(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddN(FlatBufferBuilder builder, int N) { builder.AddInt(0, N, 0); }
  public static void AddI(FlatBufferBuilder builder, int I) { builder.AddInt(1, I, 0); }
  public static void AddTime(FlatBufferBuilder builder, int time) { builder.AddInt(2, time, 0); }
  public static void AddPositions(FlatBufferBuilder builder, VectorOffset positionsOffset) { builder.AddOffset(3, positionsOffset.Value, 0); }
  public static void StartPositionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(16, numElems, 4); }
  public static void AddBonds(FlatBufferBuilder builder, VectorOffset bondsOffset) { builder.AddOffset(4, bondsOffset.Value, 0); }
  public static void StartBondsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static Offset<Frame> EndFrame(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Frame>(o);
  }
  public static void FinishFrameBuffer(FlatBufferBuilder builder, Offset<Frame> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFrameBuffer(FlatBufferBuilder builder, Offset<Frame> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
